/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "social-callback": () => import("@/views/_builtin/social-callback/index.vue"),
  "user-center": () => import("@/views/_builtin/user-center/index.vue"),
  about: () => import("@/views/about/index.vue"),
  global_activate: () => import("@/views/global/activate/index.vue"),
  global_industry: () => import("@/views/global/industry/index.vue"),
  "global_sys-screen": () => import("@/views/global/sys-screen/index.vue"),
  "global_type-device-template": () => import("@/views/global/type-device-template/index.vue"),
  home: () => import("@/views/home/index.vue"),
  integrator_intlist: () => import("@/views/integrator/intlist/index.vue"),
  integrator_version: () => import("@/views/integrator/version/index.vue"),
  "menu_integrator-menu": () => import("@/views/menu/integrator-menu/index.vue"),
  "menu_platform-menu": () => import("@/views/menu/platform-menu/index.vue"),
  "menu_project-menu": () => import("@/views/menu/project-menu/index.vue"),
  system_dept: () => import("@/views/system/dept/index.vue"),
  system_menu: () => import("@/views/system/menu/index.vue"),
  system_notice: () => import("@/views/system/notice/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  tool_gen: () => import("@/views/tool/gen/index.vue"),
};
