/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "user-center": () => import("@/views/_builtin/user-center/index.vue"),
  about: () => import("@/views/about/index.vue"),
  "corp_corp-detail": () => import("@/views/corp/corp-detail/index.vue"),
  "corp_corp-list": () => import("@/views/corp/corp-list/index.vue"),
  corp_version: () => import("@/views/corp/version/index.vue"),
  "device_device-group": () => import("@/views/device/device-group/index.vue"),
  "device_device-list": () => import("@/views/device/device-list/index.vue"),
  "device_device-type-detail": () => import("@/views/device/device-type-detail/index.vue"),
  "device_device-type": () => import("@/views/device/device-type/index.vue"),
  "gateway_gateway-list": () => import("@/views/gateway/gateway-list/index.vue"),
  global_activate: () => import("@/views/global/activate/index.vue"),
  "global_device-type-template-point": () => import("@/views/global/device-type-template-point/index.vue"),
  "global_device-type-template": () => import("@/views/global/device-type-template/index.vue"),
  global_industry: () => import("@/views/global/industry/index.vue"),
  "global_sys-screen": () => import("@/views/global/sys-screen/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "ledger_assets-type": () => import("@/views/ledger/assets-type/index.vue"),
  ledger_assets: () => import("@/views/ledger/assets/index.vue"),
  "menu_corp-menu": () => import("@/views/menu/corp-menu/index.vue"),
  "menu_platform-menu": () => import("@/views/menu/platform-menu/index.vue"),
  "menu_project-menu": () => import("@/views/menu/project-menu/index.vue"),
  monitor_operlog: () => import("@/views/monitor/operlog/index.vue"),
  "project_project-list": () => import("@/views/project/project-list/index.vue"),
  "space_space-list": () => import("@/views/space/space-list/index.vue"),
  "space_space-type": () => import("@/views/space/space-type/index.vue"),
  system_dept: () => import("@/views/system/dept/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  "system_system-log": () => import("@/views/system/system-log/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  "version_version-list": () => import("@/views/version/version-list/index.vue"),
  visual_configuration: () => import("@/views/visual/configuration/index.vue"),
  "visual_custom-screen": () => import("@/views/visual/custom-screen/index.vue"),
  "visual_sys-screen-tag": () => import("@/views/visual/sys-screen-tag/index.vue"),
  "visual_sys-screen": () => import("@/views/visual/sys-screen/index.vue"),
};
