/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'alarm',
    path: '/alarm',
    component: 'layout.base',
    meta: {
      title: 'alarm',
      i18nKey: 'route.alarm'
    },
    children: [
      {
        name: 'alarm_notice-group',
        path: '/alarm/notice-group',
        component: 'view.alarm_notice-group',
        meta: {
          title: 'alarm_notice-group',
          i18nKey: 'route.alarm_notice-group'
        }
      },
      {
        name: 'alarm_record',
        path: '/alarm/record',
        component: 'view.alarm_record',
        meta: {
          title: 'alarm_record',
          i18nKey: 'route.alarm_record'
        }
      },
      {
        name: 'alarm_rule',
        path: '/alarm/rule',
        component: 'view.alarm_rule',
        meta: {
          title: 'alarm_rule',
          i18nKey: 'route.alarm_rule'
        }
      }
    ]
  },
  {
    name: 'corp',
    path: '/corp',
    component: 'layout.base',
    meta: {
      title: 'corp',
      i18nKey: 'route.corp'
    },
    children: [
      {
        name: 'corp_corp-detail',
        path: '/corp/corp-detail',
        component: 'view.corp_corp-detail',
        meta: {
          title: 'corp_corp-detail',
          i18nKey: 'route.corp_corp-detail'
        }
      },
      {
        name: 'corp_corp-list',
        path: '/corp/corp-list',
        component: 'view.corp_corp-list',
        meta: {
          title: 'corp_corp-list',
          i18nKey: 'route.corp_corp-list'
        }
      },
      {
        name: 'corp_version',
        path: '/corp/version',
        component: 'view.corp_version',
        meta: {
          title: 'corp_version',
          i18nKey: 'route.corp_version'
        }
      }
    ]
  },
  {
    name: 'device',
    path: '/device',
    component: 'layout.base',
    meta: {
      title: 'device',
      i18nKey: 'route.device'
    },
    children: [
      {
        name: 'device_device-detail',
        path: '/device/device-detail',
        component: 'view.device_device-detail',
        meta: {
          title: 'device_device-detail',
          i18nKey: 'route.device_device-detail'
        }
      },
      {
        name: 'device_device-group',
        path: '/device/device-group',
        component: 'view.device_device-group',
        meta: {
          title: 'device_device-group',
          i18nKey: 'route.device_device-group'
        }
      },
      {
        name: 'device_device-list',
        path: '/device/device-list',
        component: 'view.device_device-list',
        meta: {
          title: 'device_device-list',
          i18nKey: 'route.device_device-list'
        }
      },
      {
        name: 'device_device-point-manage',
        path: '/device/device-point-manage',
        component: 'view.device_device-point-manage',
        meta: {
          title: 'device_device-point-manage',
          i18nKey: 'route.device_device-point-manage'
        }
      },
      {
        name: 'device_device-type',
        path: '/device/device-type',
        component: 'view.device_device-type',
        meta: {
          title: 'device_device-type',
          i18nKey: 'route.device_device-type'
        }
      },
      {
        name: 'device_device-type-detail',
        path: '/device/device-type-detail',
        component: 'view.device_device-type-detail',
        meta: {
          title: 'device_device-type-detail',
          i18nKey: 'route.device_device-type-detail'
        }
      },
      {
        name: 'device_physical-point-detail',
        path: '/device/physical-point-detail',
        component: 'view.device_physical-point-detail',
        meta: {
          title: 'device_physical-point-detail',
          i18nKey: 'route.device_physical-point-detail'
        }
      }
    ]
  },
  {
    name: 'gateway',
    path: '/gateway',
    component: 'layout.base',
    meta: {
      title: 'gateway',
      i18nKey: 'route.gateway'
    },
    children: [
      {
        name: 'gateway_gateway-list',
        path: '/gateway/gateway-list',
        component: 'view.gateway_gateway-list',
        meta: {
          title: 'gateway_gateway-list',
          i18nKey: 'route.gateway_gateway-list'
        }
      }
    ]
  },
  {
    name: 'global',
    path: '/global',
    component: 'layout.base',
    meta: {
      title: 'global',
      i18nKey: 'route.global'
    },
    children: [
      {
        name: 'global_activate',
        path: '/global/activate',
        component: 'view.global_activate',
        meta: {
          title: 'global_activate',
          i18nKey: 'route.global_activate'
        }
      },
      {
        name: 'global_device-type-template',
        path: '/global/device-type-template',
        component: 'view.global_device-type-template',
        meta: {
          title: 'global_device-type-template',
          i18nKey: 'route.global_device-type-template'
        }
      },
      {
        name: 'global_device-type-template-point',
        path: '/global/device-type-template-point',
        component: 'view.global_device-type-template-point',
        meta: {
          title: 'global_device-type-template-point',
          i18nKey: 'route.global_device-type-template-point'
        }
      },
      {
        name: 'global_industry',
        path: '/global/industry',
        component: 'view.global_industry',
        meta: {
          title: 'global_industry',
          i18nKey: 'route.global_industry'
        }
      },
      {
        name: 'global_sys-screen',
        path: '/global/sys-screen',
        component: 'view.global_sys-screen',
        meta: {
          title: 'global_sys-screen',
          i18nKey: 'route.global_sys-screen'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'ledger',
    path: '/ledger',
    component: 'layout.base',
    meta: {
      title: 'ledger',
      i18nKey: 'route.ledger'
    },
    children: [
      {
        name: 'ledger_assets',
        path: '/ledger/assets',
        component: 'view.ledger_assets',
        meta: {
          title: 'ledger_assets',
          i18nKey: 'route.ledger_assets'
        }
      },
      {
        name: 'ledger_assets-type',
        path: '/ledger/assets-type',
        component: 'view.ledger_assets-type',
        meta: {
          title: 'ledger_assets-type',
          i18nKey: 'route.ledger_assets-type'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'menu',
    path: '/menu',
    component: 'layout.base',
    meta: {
      title: 'menu',
      i18nKey: 'route.menu'
    },
    children: [
      {
        name: 'menu_corp-menu',
        path: '/menu/corp-menu',
        component: 'view.menu_corp-menu',
        meta: {
          title: 'menu_corp-menu',
          i18nKey: 'route.menu_corp-menu'
        }
      },
      {
        name: 'menu_platform-menu',
        path: '/menu/platform-menu',
        component: 'view.menu_platform-menu',
        meta: {
          title: 'menu_platform-menu',
          i18nKey: 'route.menu_platform-menu'
        }
      },
      {
        name: 'menu_project-menu',
        path: '/menu/project-menu',
        component: 'view.menu_project-menu',
        meta: {
          title: 'menu_project-menu',
          i18nKey: 'route.menu_project-menu'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'project',
    path: '/project',
    component: 'layout.base',
    meta: {
      title: 'project',
      i18nKey: 'route.project'
    },
    children: [
      {
        name: 'project_project-list',
        path: '/project/project-list',
        component: 'view.project_project-list',
        meta: {
          title: 'project_project-list',
          i18nKey: 'route.project_project-list'
        }
      }
    ]
  },
  {
    name: 'rule',
    path: '/rule',
    component: 'layout.base',
    meta: {
      title: 'rule',
      i18nKey: 'route.rule'
    },
    children: [
      {
        name: 'rule_message-rule',
        path: '/rule/message-rule',
        component: 'view.rule_message-rule',
        meta: {
          title: 'rule_message-rule',
          i18nKey: 'route.rule_message-rule'
        }
      }
    ]
  },
  {
    name: 'space',
    path: '/space',
    component: 'layout.base',
    meta: {
      title: 'space',
      i18nKey: 'route.space'
    },
    children: [
      {
        name: 'space_space-list',
        path: '/space/space-list',
        component: 'view.space_space-list',
        meta: {
          title: 'space_space-list',
          i18nKey: 'route.space_space-list'
        }
      },
      {
        name: 'space_space-type',
        path: '/space/space-type',
        component: 'view.space_space-type',
        meta: {
          title: 'space_space-type',
          i18nKey: 'route.space_space-type'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_system-log',
        path: '/system/system-log',
        component: 'view.system_system-log',
        meta: {
          title: 'system_system-log',
          i18nKey: 'route.system_system-log'
        }
      },
      {
        name: 'system_toolbox',
        path: '/system/toolbox',
        component: 'view.system_toolbox',
        meta: {
          title: 'system_toolbox',
          i18nKey: 'route.system_toolbox'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  },
  {
    name: 'version',
    path: '/version',
    component: 'layout.base',
    meta: {
      title: 'version',
      i18nKey: 'route.version'
    },
    children: [
      {
        name: 'version_version-list',
        path: '/version/version-list',
        component: 'view.version_version-list',
        meta: {
          title: 'version_version-list',
          i18nKey: 'route.version_version-list'
        }
      }
    ]
  },
  {
    name: 'visual',
    path: '/visual',
    component: 'layout.base',
    meta: {
      title: 'visual',
      i18nKey: 'route.visual'
    },
    children: [
      {
        name: 'visual_configuration',
        path: '/visual/configuration',
        component: 'view.visual_configuration',
        meta: {
          title: 'visual_configuration',
          i18nKey: 'route.visual_configuration'
        }
      },
      {
        name: 'visual_custom-screen',
        path: '/visual/custom-screen',
        component: 'view.visual_custom-screen',
        meta: {
          title: 'visual_custom-screen',
          i18nKey: 'route.visual_custom-screen'
        }
      },
      {
        name: 'visual_sys-screen',
        path: '/visual/sys-screen',
        component: 'view.visual_sys-screen',
        meta: {
          title: 'visual_sys-screen',
          i18nKey: 'route.visual_sys-screen'
        }
      },
      {
        name: 'visual_sys-screen-tag',
        path: '/visual/sys-screen-tag',
        component: 'view.visual_sys-screen-tag',
        meta: {
          title: 'visual_sys-screen-tag',
          i18nKey: 'route.visual_sys-screen-tag'
        }
      }
    ]
  },
  {
    name: 'workorder',
    path: '/workorder',
    component: 'layout.base',
    meta: {
      title: 'workorder',
      i18nKey: 'route.workorder'
    },
    children: [
      {
        name: 'workorder_workorder-list',
        path: '/workorder/workorder-list',
        component: 'view.workorder_workorder-list',
        meta: {
          title: 'workorder_workorder-list',
          i18nKey: 'route.workorder_workorder-list'
        }
      }
    ]
  }
];
