/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'corp',
    path: '/corp',
    component: 'layout.base',
    meta: {
      title: 'corp',
      i18nKey: 'route.corp'
    },
    children: [
      {
        name: 'corp_corp-detail',
        path: '/corp/corp-detail',
        component: 'view.corp_corp-detail',
        meta: {
          title: 'corp_corp-detail',
          i18nKey: 'route.corp_corp-detail'
        }
      },
      {
        name: 'corp_corp-list',
        path: '/corp/corp-list',
        component: 'view.corp_corp-list',
        meta: {
          title: 'corp_corp-list',
          i18nKey: 'route.corp_corp-list'
        }
      },
      {
        name: 'corp_version',
        path: '/corp/version',
        component: 'view.corp_version',
        meta: {
          title: 'corp_version',
          i18nKey: 'route.corp_version'
        }
      }
    ]
  },
  {
    name: 'global',
    path: '/global',
    component: 'layout.base',
    meta: {
      title: 'global',
      i18nKey: 'route.global'
    },
    children: [
      {
        name: 'global_activate',
        path: '/global/activate',
        component: 'view.global_activate',
        meta: {
          title: 'global_activate',
          i18nKey: 'route.global_activate'
        }
      },
      {
        name: 'global_device-type-template',
        path: '/global/device-type-template',
        component: 'view.global_device-type-template',
        meta: {
          title: 'global_device-type-template',
          i18nKey: 'route.global_device-type-template'
        }
      },
      {
        name: 'global_device-type-template-point',
        path: '/global/device-type-template-point',
        component: 'view.global_device-type-template-point',
        meta: {
          title: 'global_device-type-template-point',
          i18nKey: 'route.global_device-type-template-point'
        }
      },
      {
        name: 'global_industry',
        path: '/global/industry',
        component: 'view.global_industry',
        meta: {
          title: 'global_industry',
          i18nKey: 'route.global_industry'
        }
      },
      {
        name: 'global_sys-screen',
        path: '/global/sys-screen',
        component: 'view.global_sys-screen',
        meta: {
          title: 'global_sys-screen',
          i18nKey: 'route.global_sys-screen'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'menu',
    path: '/menu',
    component: 'layout.base',
    meta: {
      title: 'menu',
      i18nKey: 'route.menu'
    },
    children: [
      {
        name: 'menu_corp-menu',
        path: '/menu/corp-menu',
        component: 'view.menu_corp-menu',
        meta: {
          title: 'menu_corp-menu',
          i18nKey: 'route.menu_corp-menu'
        }
      },
      {
        name: 'menu_platform-menu',
        path: '/menu/platform-menu',
        component: 'view.menu_platform-menu',
        meta: {
          title: 'menu_platform-menu',
          i18nKey: 'route.menu_platform-menu'
        }
      },
      {
        name: 'menu_project-menu',
        path: '/menu/project-menu',
        component: 'view.menu_project-menu',
        meta: {
          title: 'menu_project-menu',
          i18nKey: 'route.menu_project-menu'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  },
  {
    name: 'version',
    path: '/version',
    component: 'layout.base',
    meta: {
      title: 'version',
      i18nKey: 'route.version'
    },
    children: [
      {
        name: 'version_version-list',
        path: '/version/version-list',
        component: 'view.version_version-list',
        meta: {
          title: 'version_version-list',
          i18nKey: 'route.version_version-list'
        }
      }
    ]
  }
];
