/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'global',
    path: '/global',
    component: 'layout.base',
    meta: {
      title: 'global',
      i18nKey: 'route.global'
    },
    children: [
      {
        name: 'global_activate',
        path: '/global/activate',
        component: 'view.global_activate',
        meta: {
          title: 'global_activate',
          i18nKey: 'route.global_activate'
        }
      },
      {
        name: 'global_industry',
        path: '/global/industry',
        component: 'view.global_industry',
        meta: {
          title: 'global_industry',
          i18nKey: 'route.global_industry'
        }
      },
      {
        name: 'global_sys-screen',
        path: '/global/sys-screen',
        component: 'view.global_sys-screen',
        meta: {
          title: 'global_sys-screen',
          i18nKey: 'route.global_sys-screen'
        }
      },
      {
        name: 'global_type-device-template',
        path: '/global/type-device-template',
        component: 'view.global_type-device-template',
        meta: {
          title: 'global_type-device-template',
          i18nKey: 'route.global_type-device-template'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'integrator',
    path: '/integrator',
    component: 'layout.base',
    meta: {
      title: 'integrator',
      i18nKey: 'route.integrator'
    },
    children: [
      {
        name: 'integrator_intlist',
        path: '/integrator/intlist',
        component: 'view.integrator_intlist',
        meta: {
          title: 'integrator_intlist',
          i18nKey: 'route.integrator_intlist'
        }
      },
      {
        name: 'integrator_version',
        path: '/integrator/version',
        component: 'view.integrator_version',
        meta: {
          title: 'integrator_version',
          i18nKey: 'route.integrator_version'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'menu',
    path: '/menu',
    component: 'layout.base',
    meta: {
      title: 'menu',
      i18nKey: 'route.menu'
    },
    children: [
      {
        name: 'menu_integrator-menu',
        path: '/menu/integrator-menu',
        component: 'view.menu_integrator-menu',
        meta: {
          title: 'menu_integrator-menu',
          i18nKey: 'route.menu_integrator-menu'
        }
      },
      {
        name: 'menu_platform-menu',
        path: '/menu/platform-menu',
        component: 'view.menu_platform-menu',
        meta: {
          title: 'menu_platform-menu',
          i18nKey: 'route.menu_platform-menu'
        }
      },
      {
        name: 'menu_project-menu',
        path: '/menu/project-menu',
        component: 'view.menu_project-menu',
        meta: {
          title: 'menu_project-menu',
          i18nKey: 'route.menu_project-menu'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  }
];
