/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          meta: {
            title: route.meta?.title || ''
          },
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }

  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "exception": "/exception",
  "exception_403": "/exception/403",
  "exception_404": "/exception/404",
  "exception_500": "/exception/500",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "about": "/about",
  "alarm": "/alarm",
  "alarm_notice-group": "/alarm/notice-group",
  "alarm_record": "/alarm/record",
  "alarm_rule": "/alarm/rule",
  "corp": "/corp",
  "corp_corp-detail": "/corp/corp-detail",
  "corp_corp-list": "/corp/corp-list",
  "corp_version": "/corp/version",
  "device": "/device",
  "device_device-detail": "/device/device-detail",
  "device_device-group": "/device/device-group",
  "device_device-list": "/device/device-list",
  "device_device-point-manage": "/device/device-point-manage",
  "device_device-type": "/device/device-type",
  "device_device-type-detail": "/device/device-type-detail",
  "device_physical-point-detail": "/device/physical-point-detail",
  "device_virtual-point": "/device/virtual-point",
  "effroom": "/effroom",
  "effroom_energy-calendar": "/effroom/energy-calendar",
  "effroom_overview": "/effroom/overview",
  "effroom_point-compare": "/effroom/point-compare",
  "energy": "/energy",
  "energy_energy-list": "/energy/energy-list",
  "energy_run-time": "/energy/run-time",
  "gateway": "/gateway",
  "gateway_gateway-list": "/gateway/gateway-list",
  "global": "/global",
  "global_activate": "/global/activate",
  "global_device-type-template": "/global/device-type-template",
  "global_device-type-template-point": "/global/device-type-template-point",
  "global_industry": "/global/industry",
  "global_sys-screen": "/global/sys-screen",
  "home": "/home",
  "iframe-page": "/iframe-page/:url",
  "ledger": "/ledger",
  "ledger_assets": "/ledger/assets",
  "ledger_assets-type": "/ledger/assets-type",
  "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?",
  "menu": "/menu",
  "menu_corp-menu": "/menu/corp-menu",
  "menu_platform-menu": "/menu/platform-menu",
  "menu_project-menu": "/menu/project-menu",
  "monitor": "/monitor",
  "monitor_monitor-device": "/monitor/monitor-device",
  "monitor_player": "/monitor/player",
  "monitor_producer": "/monitor/producer",
  "project": "/project",
  "project_project-list": "/project/project-list",
  "rule": "/rule",
  "rule_message-rule": "/rule/message-rule",
  "space": "/space",
  "space_space-list": "/space/space-list",
  "space_space-type": "/space/space-type",
  "system": "/system",
  "system_dept": "/system/dept",
  "system_role": "/system/role",
  "system_system-log": "/system/system-log",
  "system_toolbox": "/system/toolbox",
  "system_user": "/system/user",
  "task": "/task",
  "task_task-list": "/task/task-list",
  "task_task-log": "/task/task-log",
  "user-center": "/user-center",
  "version": "/version",
  "version_version-list": "/version/version-list",
  "visual": "/visual",
  "visual_configuration": "/visual/configuration",
  "visual_custom-screen": "/visual/custom-screen",
  "visual_fuxa": "/visual/fuxa",
  "visual_sys-screen": "/visual/sys-screen",
  "visual_sys-screen-tag": "/visual/sys-screen-tag",
  "workorder": "/workorder",
  "workorder_workorder-list": "/workorder/workorder-list"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
