/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "about": "/about";
    "alarm": "/alarm";
    "alarm_notice-group": "/alarm/notice-group";
    "alarm_record": "/alarm/record";
    "alarm_rule": "/alarm/rule";
    "corp": "/corp";
    "corp_corp-detail": "/corp/corp-detail";
    "corp_corp-list": "/corp/corp-list";
    "corp_version": "/corp/version";
    "datahub": "/datahub";
    "datahub_rule": "/datahub/rule";
    "device": "/device";
    "device_device-detail": "/device/device-detail";
    "device_device-group": "/device/device-group";
    "device_device-list": "/device/device-list";
    "device_device-point-manage": "/device/device-point-manage";
    "device_device-type": "/device/device-type";
    "device_device-type-detail": "/device/device-type-detail";
    "device_physical-point-detail": "/device/physical-point-detail";
    "device_virtual-point": "/device/virtual-point";
    "effroom": "/effroom";
    "effroom_energy-calendar": "/effroom/energy-calendar";
    "effroom_overview": "/effroom/overview";
    "effroom_point-compare": "/effroom/point-compare";
    "energy": "/energy";
    "energy_energy-list": "/energy/energy-list";
    "energy_run-time": "/energy/run-time";
    "gateway": "/gateway";
    "gateway_gateway-list": "/gateway/gateway-list";
    "global": "/global";
    "global_activate": "/global/activate";
    "global_device-type-template": "/global/device-type-template";
    "global_device-type-template-point": "/global/device-type-template-point";
    "global_industry": "/global/industry";
    "global_sys-screen": "/global/sys-screen";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "ledger": "/ledger";
    "ledger_assets": "/ledger/assets";
    "ledger_assets-type": "/ledger/assets-type";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "menu": "/menu";
    "menu_corp-menu": "/menu/corp-menu";
    "menu_platform-menu": "/menu/platform-menu";
    "menu_project-menu": "/menu/project-menu";
    "monitor": "/monitor";
    "monitor_monitor-device": "/monitor/monitor-device";
    "monitor_player": "/monitor/player";
    "monitor_producer": "/monitor/producer";
    "project": "/project";
    "project_project-list": "/project/project-list";
    "rule": "/rule";
    "rule_message-rule": "/rule/message-rule";
    "space": "/space";
    "space_space-list": "/space/space-list";
    "space_space-type": "/space/space-type";
    "system": "/system";
    "system_dept": "/system/dept";
    "system_role": "/system/role";
    "system_system-log": "/system/system-log";
    "system_toolbox": "/system/toolbox";
    "system_user": "/system/user";
    "task": "/task";
    "task_task-list": "/task/task-list";
    "task_task-log": "/task/task-log";
    "user-center": "/user-center";
    "version": "/version";
    "version_version-list": "/version/version-list";
    "visual": "/visual";
    "visual_configuration": "/visual/configuration";
    "visual_custom-screen": "/visual/custom-screen";
    "visual_fuxa": "/visual/fuxa";
    "visual_sys-screen": "/visual/sys-screen";
    "visual_sys-screen-tag": "/visual/sys-screen-tag";
    "workorder": "/workorder";
    "workorder_workorder-list": "/workorder/workorder-list";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "about"
    | "alarm"
    | "corp"
    | "datahub"
    | "device"
    | "effroom"
    | "energy"
    | "gateway"
    | "global"
    | "home"
    | "iframe-page"
    | "ledger"
    | "login"
    | "menu"
    | "monitor"
    | "project"
    | "rule"
    | "space"
    | "system"
    | "task"
    | "user-center"
    | "version"
    | "visual"
    | "workorder"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "user-center"
    | "about"
    | "alarm_notice-group"
    | "alarm_record"
    | "alarm_rule"
    | "corp_corp-detail"
    | "corp_corp-list"
    | "corp_version"
    | "datahub_rule"
    | "device_device-detail"
    | "device_device-group"
    | "device_device-list"
    | "device_device-point-manage"
    | "device_device-type-detail"
    | "device_device-type"
    | "device_physical-point-detail"
    | "device_virtual-point"
    | "effroom_energy-calendar"
    | "effroom_overview"
    | "effroom_point-compare"
    | "energy_energy-list"
    | "energy_run-time"
    | "gateway_gateway-list"
    | "global_activate"
    | "global_device-type-template-point"
    | "global_device-type-template"
    | "global_industry"
    | "global_sys-screen"
    | "home"
    | "ledger_assets-type"
    | "ledger_assets"
    | "menu_corp-menu"
    | "menu_platform-menu"
    | "menu_project-menu"
    | "monitor_monitor-device"
    | "monitor_player"
    | "monitor_producer"
    | "project_project-list"
    | "rule_message-rule"
    | "space_space-list"
    | "space_space-type"
    | "system_dept"
    | "system_role"
    | "system_system-log"
    | "system_toolbox"
    | "system_user"
    | "task_task-list"
    | "task_task-log"
    | "version_version-list"
    | "visual_configuration"
    | "visual_custom-screen"
    | "visual_fuxa"
    | "visual_sys-screen-tag"
    | "visual_sys-screen"
    | "workorder_workorder-list"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
